### ISSUE TITLE
作者你好，我在download下来的压缩包中找到了apk文件，但是安装后加载不出内容

### ISSUE THREAD

**Issue by OTraveler** [wqandroid/avflutter#5]
作者你好，我在download下来的压缩包中找到了apk文件，但是安装后加载不出内容

**Comment by wqandroid** [comment]
那个apk 是之前的不能用了。这个项目需要自己编译打包apk。或者编译工程在手机运行就ok

**Comment by SmllXzBZ** [comment]
请问需要用什么软件进行打包？利用flutter进行打包吗

**Comment by OTraveler** [comment]
> 请问需要用什么软件进行打包？利用flutter进行打包吗

as吧，环境没配好我就没去弄了

**Comment by godBlessUp** [comment]
不行啊，在手机加载也不出内容，api问题吧
